on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI/CD Automation
    steps:
      - uses: actions/checkout@v3
      - name: Automation step 1
        uses: ./.github/
